### ISSUE TITLE
crash on launching Catherine

### ISSUE THREAD

**Issue by butstevetho** [cuevavirus/hdpatch#1]
I am sure that sharpscale and catherinefbhd.suprx are installed properly, and configured properly as well. When the game gets to the Atlus/Criware logos, the game always crashes (C2-12828-1)

Furthermore, I notice that throughout the time leading up to the crash (network loading, fan translation disclaimer), the text "Catherine Full Body HD Patch success: 1280x720" persists the entire time, never goes away.

I am using a PS Vita 1000 model with 3.65 enso

**Comment by cuevavirus** [comment]
Maybe a conflict if you have other user plugins.

**Comment by butstevetho** [comment]
I'll start disabling them and see which are the culprit. Are there any common offenders?

**Comment by butstevetho** [comment]
Here's my config.txt. Am I doing something wrong here?

`*KERNEL
ur0:tai/storagemgr.skprx
ur0:tai/sharpscale.skprx
ur0:tai/LOLIcon.skprx
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
# henkaku.skprx is hard-coded to load and is not listed here
ur0:tai/0syscall6.skprx
ur0:tai/nonpdrm.skprx
ur0:tai/ioPlus.skprx
ur0:tai/repatch.skprx
ur0:tai/kuio.skprx 
ur0:vitacheat/vitacheat.skprx
ur0:tai/vitabright.skprx
ur0:tai/ds3vita.skprx
ur0:tai/udcd_uvc_oled_off.skprx
*main
ur0:tai/shellsecbat.suprx
ur0:tai/download_enabler.suprx
ur0:tai/henkaku.suprx
*PCSG01179
ur0:tai/catherinefbhd.suprx
*PCSG00141
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
*!PSPEMUCFW
*ALL`

**Comment by butstevetho** [comment]
Update: interestingly, your Persona 4 Golden 1280x720 and 1920x1080 suprx plugins work perfectly fine for me. It's just the catherine patch specifically, i can now confirm.
