### ISSUE TITLE
Crashes during app startup

### ISSUE THREAD

**Issue by MDiGIaC7** [cuevavirus/hdpatch#2]
PS Vita 3.60 henkaku w/ Enso v2 running SD2Vita 128gb

After inserting the patch .suprx to the tai directory in my ux0 and updating the config file appropriately, everytime I start the Catherine game on my Vita it brings me to a screen that is almost partitioned in 4 areas with a message I can barely read that says it's "reapplying" something. 

After this, a screen pops up in a simple black background format with a progress bar that looks like such "[********]" and says:

"An error as occurred. The PS Vita system will be powered off."

It's worth noting that I have a similar 720p patch I use on P4G and that works just fine. As a precaution, I disabled VitaGrafix for this title and P4G, both of which have HD patches that load seperately.

**Comment by cuevavirus** [comment]
Can you please post your config.txt

**Comment by MDiGIaC7** [comment]
Absolutely. 

It's worth noting that though I've successfully hacked it, I have occasional troubles booting up from a complete power down. I believe this issue is related to the initial boot of the system not loading the proper taiHEN config.txt. It's located in ur0, despite many plugins existing in the ux0 directory. There is no config file in my ux0 tai folder.

I believe this is the issue that's preventing me from running Adrenaline, I haven't been able to install it properly without bricking my Vita so far.

I'm sorry for my rambling on an unrelated topic, you're definitely someone to turn to with these miscellaneous issues.

**********
config.txt
**********

*main
# main is a special titleid for SceShell
ux0:tai/henkaku.suprx
ux0:/tai/nolockscreen.suprx
ux0:/tai/quick_power.suprx
ux0:/tai/quick_volume.suprx
ux0:/tai/shellbat.suprx
ux0:/tai/jav.suprx
ux0:/tai/TrImpose.suprx
*NPXS10015
# this is for modifying the version string
ux0:tai/henkaku.suprx
ux0:/tai/macspoofer.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ux0:tai/henkaku.suprx
ux0:/tai/macspoofer.suprx
*KERNEL
ux0:tai/storagemgr.skprx
ux0:tai/nonpdrm.skprx
ux0:tai/reF00D.skprx
ux0:tai/0syscall6.skprx
ux0:tai/repatch.skprx
ux0:tai/sharpscale.skprx
ux0:/tai/cidSpoof.skprx
ux0:/tai/CpuAffinityChanger.skprx
ux0:/tai/music_premium.skprx
ux0:/tai/NoPowerLimits.skprx
ux0:/tai/nosleep.skprx
ux0:/tai/rapidmenu.skprx
ux0:/tai/vitabright.skprx
ux0:/tai/ioplus.skprx
ux0:/tai/ds3vita.skprx
ux0:/tai/ds4vita.skprx
ux0:/tai/udcd_uvc_oled_off.skprx
*PCSE00120
ux0:/tai/p4goldenhd_1280x720.suprx
*PCSG01179
ux0:/tai/catherinefbhd.suprx
!AKRK00005

!AKRK00005

*ALL
ux0:/tai/forcelang.suprx
ux0:/tai/Framecounter.suprx
ux0:/tai/oclockvita.suprx
ux0:/tai/reRescaler.suprx
ux0:/tai/trophax2.0.suprx
ux0:/tai/VitaGrafix.suprx

**Comment by cuevavirus** [comment]
Probably a conflict with rerescaler, try adding a line `*!PCSG01179` before `*ALL`.

**Comment by MDiGIaC7** [comment]
Added that line in both configs but no luck, same error and same screen.

**Comment by cuevavirus** [comment]
[catherinefbhd.zip](https://github.com/cuevavirus/hdpatch/files/4849921/catherinefbhd.zip)

Can you try this build and upload the log file from `ux0:temp/catherinefbhd.txt`.

**Comment by MDiGIaC7** [comment]
Thanks for your patience, it was late here last night and I went to bed otherwise would have responded sooner. 

Happy to report that this patch did indeed work, I was able to boot to my last save file and the resolution was noticeably improved, but I found myself unable to use some (possibly all) of my other plugins, notably the overclock plugin. The performance in-game tanked too. It was running probably around 10 FPS or so, definitely no more than 15.

Unfortunately, I found no such .txt file in the temp folder in ux0

**Comment by cuevavirus** [comment]
I recommend using a kernel plugin for overclocking, such as lolicon or psvshell. The log file creation requires ioplus but I see that you have it already. Maybe try the one from the forum post again since the logged build is working. There is really no difference between the two besides the logging.

**Comment by MDiGIaC7** [comment]
Very interesting, you're right! Not sure what may have changed but after reinstalling the release from the forum it's working now, and with all the other plugins.

Thanks for all your help, it's very appreciated. Keep up the great work!
